name: Pre-release
on:
  push:
    # only for tags such as 1.0.1-pre
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-pre'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 21
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build with gradle
        run: ./gradlew build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lib-artifacts # includes JARs
          path: "build/libs"
          retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          name: lib-artifacts
          path: "build/libs"
      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          prerelease: true
          draft: false
          skipIfReleaseExists: true
          generateReleaseNotes: true
          artifacts: "build/libs/*.jar"