name: Release
on:
  push:
    # only for tags such as 1.0.1
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:

  # a release may only be created from master branch
  exit-on-invalid-branch:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Checking if tag is on the master branch..."
      - name: Exit if not on master branch
        if: endsWith(github.event.base_ref, 'master') == false
        run: exit -1

  build:
    runs-on: ubuntu-latest
    needs: exit-on-invalid-branch
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with gradle
        run: ./gradlew build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lib-artifacts # includes JARs
          path: "build/libs"
          retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          name: lib-artifacts
          path: "build/libs"
      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          prerelease: false
          draft: false
          skipIfReleaseExists: true
          generateReleaseNotes: true
          artifacts: "build/libs/*.jar"